/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author mhscm
 */
public class JFrmLglPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrmLglPrincipal.class.getName());

    /**
     * Creates new form JFrmLglPrincipal
     */
    public JFrmLglPrincipal() {
        initComponents();
        setTitle("Mecânica Lino - Inicio");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuLglCadastro = new javax.swing.JMenu();
        jMnuLglUsuarios = new javax.swing.JMenuItem();
        jMnuLglClientes = new javax.swing.JMenuItem();
        jMnuLglFornecedor = new javax.swing.JMenuItem();
        jMnuLglProdutos = new javax.swing.JMenuItem();
        jMnuLglVeiculos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuLglSair = new javax.swing.JMenuItem();
        jMnuLglMovimento = new javax.swing.JMenu();
        jMnuLglCompras = new javax.swing.JMenuItem();
        jMnuLglVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuLglCadastro.setMnemonic('c');
        jMnuLglCadastro.setText("Cadastro");

        jMnuLglUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLglUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuLglUsuarios.setText("Usuários");
        jMnuLglUsuarios.addActionListener(this::jMnuLglUsuariosActionPerformed);
        jMnuLglCadastro.add(jMnuLglUsuarios);

        jMnuLglClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLglClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuLglClientes.setText("Clientes");
        jMnuLglClientes.addActionListener(this::jMnuLglClientesActionPerformed);
        jMnuLglCadastro.add(jMnuLglClientes);

        jMnuLglFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLglFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor2.png"))); // NOI18N
        jMnuLglFornecedor.setText("Fornecedor");
        jMnuLglFornecedor.addActionListener(this::jMnuLglFornecedorActionPerformed);
        jMnuLglCadastro.add(jMnuLglFornecedor);

        jMnuLglProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLglProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuLglProdutos.setText("Produtos");
        jMnuLglProdutos.addActionListener(this::jMnuLglProdutosActionPerformed);
        jMnuLglCadastro.add(jMnuLglProdutos);

        jMnuLglVeiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLglVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/veiculos.png"))); // NOI18N
        jMnuLglVeiculos.setText("Veiculos");
        jMnuLglVeiculos.addActionListener(this::jMnuLglVeiculosActionPerformed);
        jMnuLglCadastro.add(jMnuLglVeiculos);
        jMnuLglCadastro.add(jSeparator1);

        jMnuLglSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLglSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuLglSair.setText("Sair");
        jMnuLglSair.addActionListener(this::jMnuLglSairActionPerformed);
        jMnuLglCadastro.add(jMnuLglSair);

        jMenuBar1.add(jMnuLglCadastro);

        jMnuLglMovimento.setMnemonic('m');
        jMnuLglMovimento.setText("Movimento");

        jMnuLglCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuLglCompras.setText("Compras");
        jMnuLglMovimento.add(jMnuLglCompras);

        jMnuLglVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuLglVendas.setText("Vendas");
        jMnuLglMovimento.add(jMnuLglVendas);

        jMenuBar1.add(jMnuLglMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuLglUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLglUsuariosActionPerformed
        // TODO add your handling code here:
         JDlgLglUsuarios dialog = new JDlgLglUsuarios(this, true);
dialog.setVisible(true);
    }//GEN-LAST:event_jMnuLglUsuariosActionPerformed

    private void jMnuLglProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLglProdutosActionPerformed
        // TODO add your handling code here:
        JDlgLglProdutos dialog = new JDlgLglProdutos(this, true);
dialog.setVisible(true);
    }//GEN-LAST:event_jMnuLglProdutosActionPerformed

    private void jMnuLglSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLglSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuLglSairActionPerformed

    private void jMnuLglVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLglVeiculosActionPerformed
        // TODO add your handling code here:
         JDlgLglVeiculos dialog = new JDlgLglVeiculos(this, true);
dialog.setVisible(true);
    }//GEN-LAST:event_jMnuLglVeiculosActionPerformed

    private void jMnuLglFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLglFornecedorActionPerformed
        // TODO add your handling code here:
         JDlgLglFornecedor dialog = new JDlgLglFornecedor(this, true);
dialog.setVisible(true);
    }//GEN-LAST:event_jMnuLglFornecedorActionPerformed

    private void jMnuLglClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLglClientesActionPerformed
        // TODO add your handling code here:
         JDlgLglClientes dialog = new JDlgLglClientes(this, true);
dialog.setVisible(true);
    }//GEN-LAST:event_jMnuLglClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrmLglPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuLglCadastro;
    private javax.swing.JMenuItem jMnuLglClientes;
    private javax.swing.JMenuItem jMnuLglCompras;
    private javax.swing.JMenuItem jMnuLglFornecedor;
    private javax.swing.JMenu jMnuLglMovimento;
    private javax.swing.JMenuItem jMnuLglProdutos;
    private javax.swing.JMenuItem jMnuLglSair;
    private javax.swing.JMenuItem jMnuLglUsuarios;
    private javax.swing.JMenuItem jMnuLglVeiculos;
    private javax.swing.JMenuItem jMnuLglVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
